defaultPortal: Andile
portals:
  - name: Andile
    portalId: 47574277
    env: prod
    authType: personalaccesskey
    personalAccessKey: >-
      CiRuYTEtYjExOS1jNTA0LTQ3NWUtOGVmNi0yNDNhMGU1MWQyYjgQhdrXFhi92K0mKhkABeaRgjHjrK3aw3v_krITXOfskIzL_C1OSgNuYTE
    environment: standard
    projectSettings:
      srcDir: src
      autoupload: true
      server:
        port: 5175
    accountType: STANDARD
    auth:
      tokenInfo:
        accessToken: >-
          CIOfw5OBMxIoQlNQMl8kQEwrAhsACAkCARMcAQIBAgENAwoBAgMHBRYBAQEBDwEyARiF2tcWIL3YrSYo7ukMMhQP8st4DLziB5uzrSTPWKKE84oJ1DpMQlNQMl8kQEwrAj8ACBMGBh0BAQFRKxwBAQEBKAEBAQgBBgIDARAEDwEIBAEBAQEBBAEFARIGAwMBMQEBAQQBAQEBAQEBARUBM1oaAUIUXO8UhCFv-ikvTDLCqg9gan-zE5pKA25hMVIAWgBgAWi92K0mcAB4AA
        expiresAt: '2025-07-16T08:53:59.845Z'
